function s = emptyScan()
%EMPTYSCAN  Return an empty Scan struct with all standard fields.
%   s = xrdc.io.emptyScan()
%
%   Every parser in +xrdc/+io/ returns a struct with this shape:
%
%     .twoTheta       (Nx1 double, degrees)
%     .counts         (Nx1 double, raw counts; no rounding)
%     .scanType       (string)  — "twoThetaOmega" | "omega" | "phi" | "psi"
%                                  | "theta" | "area" | "unknown"
%     .secondAxis     (scalar)  — value of the constant axis; NaN if n/a
%     .secondAxisName (string)  — human name of the constant axis
%     .identifier     (string)  — short label (filename stem by default)
%     .lambda         (scalar)  — X-ray wavelength in Å, if known; NaN otherwise
%     .metadata       (struct)  — full parsed header for traceability
%     .sourcePath     (string)  — original file path
%     .sourceFormat   (string)  — "xrdml" | "philipsX00" | "text" | "rigakuRas" | "rigakuRaw"
%
%   Use this as the canonical shape for every scan in memory.

    s = struct( ...
        'twoTheta',       zeros(0,1), ...
        'counts',         zeros(0,1), ...
        'scanType',       "unknown", ...
        'secondAxis',     NaN, ...
        'secondAxisName', "", ...
        'identifier',     "", ...
        'lambda',         NaN, ...
        'metadata',       struct(), ...
        'sourcePath',     "", ...
        'sourceFormat',   "");
end
